version: '3'

services:
    frontend:
     build:
       context: ../
       dockerfile: ./docker/frontend/Dockerfile
       args:
        environment: ${environment}
        product: ${product}
        service: ${service}
        executePath: ${executePath}
        BUILD_NUMBER: ${BUILD_NUMBER}
        joker: ${joker}
